config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations' }
  	resources :snippets do
  		member do
  			put "like", to: "snippets#upvote"
        put 'dislike', to: 'snippets#dislike'
        put 'unvote', to: 'snippets#unvote'
  		end
      
      resources :comments do
        member do
          put "like", to: "comments#upvote"
          put 'dislike', to: 'comments#dislike'
          put 'unvote', to: 'comments#unvote'
        end
      end
  	end

  	root 'snippets#home'

  	get '/css', to: 'snippets#css'
    get '/javascript', to: 'snippets#javascript'
    get '/ruby', to: 'snippets#ruby'
    get '/python', to: 'snippets#python'
    get '/about', to: 'sections#about'
    get '/playground', to: 'sections#playground'
    get 'users/leaderboard' => 'users#leaderboard'
    get '/users/:id', :to => 'users#show', :as => :user
end

app/models/comment.rb
class Comment < ActiveRecord::Base
	acts_as_votable
	belongs_to :user
	belongs_to :snippet

	validates :body, presence: true, length: { in: 5..1500, :message => "Must be 5-1500 characters long" }

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	before_action :find_comment, only: [:show, :edit, :update, :destroy, :upvote, :dislike, :unvote]
	before_action :authenticate_user!

	def index
		@comments = Comment.all
	end

	def show
	end

	def new
		@comment = Comment.new
	end

	def edit
	end

	def create
		@snippet = Snippet.find(params[:snippet_id])
		@comment = @snippet.comments.new(comment_params)
		@comment.user = current_user

		respond_to do |format|
			if @comment.save
				format.html { redirect_to @snippet, notice: 'Comment successfully created.' }
				format.json { render json: @comment, status: :created, location: @comment }
			else
				format.html { render action: 'new' }
				format.json { render json: @comment.errors, status: :unprocessable_entity }
			end
		end
	end

	def update
		@snippet = Snippet.find(params[:snippet_id])
		respond_to do |format|
			if @comment.update(comment_params)
				format.html { redirect_to @snippet, notice: "Comment successfully updated." }
				format.json { render :show, status: :ok, location: @comment }
			else
				format.html { render :edit }
				format.json { render json: @comment.errors, status: :unprocessable_entity }
			end
		end
	end

	def destroy
		@comment.destroy
		respond_to do |format|
			format.html { redirect_to :back, notice: 'Comment successfully deleted.' }
			format.json { head :no_content }
		end
	end

	def upvote
		@comment.upvote_by current_user
		redirect_to :back
	end

	def dislike
		@comment.downvote_by current_user
		redirect_to :back
	end

	def unvote
		@comment.unvote_by current_user
		redirect_to :back
	end

	private
	def find_comment
		@comment = Comment.find(params[:id])
	end

	def comment_params
		params.require(:comment).permit(:snippet_id, :body, :user_id)
	end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<div class="comments">
	<%= div_for(comment) do %>
		<% if comment.user == current_user -%>

			<%= link_to image_tag("/assets/delete.png"), [comment.snippet, comment], method: :delete, :title => "Delete comment", data: {confirm: 'Are you sure?'} %>
			<%= link_to image_tag("/assets/edit.png"), edit_snippet_comment_path(@snippet, comment), :title => "Edit comment" %>

		<% else %>

			<%= link_to like_snippet_comment_path(@snippet, comment), method: :put do %>
					<%= image_tag("/assets/up.png", class: "comment-votes", :title => "Upvote comment")  %>
			<% end %>

			<%= link_to dislike_snippet_comment_path(@snippet, comment), method: :put do %>
					<%= image_tag("/assets/down.png", class: "comment-votes", :title => "Downvote comment") %>
			<% end %>
			
			<% unless comment.weighted_score == 0 %>
			<p class="comment-score"><%= comment.weighted_score %></p>
			<% end %>

		<% end %>

		<% if comment.updated_at != comment.created_at %>
    		<p id="comment-name"><%= comment.user.name %><span id="edited-comment"> (edited)</span></p>
		<% else %>
    		<p id="comment-name"><%= comment.user.name %></p>
		<% end %>
		
		<p id="comment-date"><span id="hashtag">#</span><%= (comment.created_at).strftime("%B %d, %Y") %></p>
		<pre id="comment-body"><%= markdown (auto_link(comment.body)) %></pre>
	<% end %>
</div>

app/views/comments/_form.html.erb
<div class="centered">
<div class="edit">
	<div class="edit-comment">
	<h2>Edit:</h2>
 		<%= simple_form_for [@comment.snippet, @comment]  do |f| %>
	  		<%= f.error_notification %>
	    	<%= f.input :body, :error_html => { :class => "form-error"} %>
	    	<br>
	    	<%= f.button :submit %>
		<% end %>
	</div>
</div>
</div>

app/views/comments/edit.html.erb
<%= render 'form' %>

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Comments</h1>

<table>
  <thead>
    <tr>
      <th>Snippet</th>
      <th>Body</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.snippet_id %></td>
        <td><%= comment.body %></td>
        <td><%= comment.user %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<%= render 'form' %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Link:</strong>
  <%= @comment.link_id %>
</p>

<p>
  <strong>Body:</strong>
  <%= @comment.body %>
</p>

<p>
  <strong>User:</strong>
  <%= @comment.user %>
</p>