config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations' }
  	resources :snippets do
  		member do
  			put "like", to: "snippets#upvote"
        put 'dislike', to: 'snippets#dislike'
        put 'unvote', to: 'snippets#unvote'
  		end
      
      resources :comments do
        member do
          put "like", to: "comments#upvote"
          put 'dislike', to: 'comments#dislike'
          put 'unvote', to: 'comments#unvote'
        end
      end
  	end

  	root 'snippets#home'

  	get '/css', to: 'snippets#css'
    get '/javascript', to: 'snippets#javascript'
    get '/ruby', to: 'snippets#ruby'
    get '/python', to: 'snippets#python'
    get '/about', to: 'sections#about'
    get '/playground', to: 'sections#playground'
    get 'users/leaderboard' => 'users#leaderboard'
    get '/users/:id', :to => 'users#show', :as => :user
end

app/models/snippet.rb
class Snippet < ActiveRecord::Base
	acts_as_votable
	belongs_to :category
	belongs_to :user
	has_many :comments

	validates :category_id, presence: true
	validates :title, presence: true, length: { in: 5..35, :message => "Must be 5-35 characters long" }

	validate :any_present?

	def any_present?
  		if html.blank? and css.blank? and javascript.blank? and ruby.blank? and python.blank?
    		errors.add(:title, "You must include at least one languages code")
  		end
	end

    # Home page
    scope :random, -> { order("RANDOM()").limit(1) }
    scope :upvotedSnippet, -> { order(:cached_votes_up => :desc).limit(1) }
	scope :totalVotes, -> { sum(:cached_votes_total) }
	scope :totalUpVotes, -> { sum(:cached_votes_up) }
	scope :totalDownVotes, -> { sum(:cached_votes_down) }

	# Created at descending order by time
	scope :desc, -> { order("created_at DESC") }

	def self.search(search)
    	where("title LIKE ? OR css LIKE ? OR html LIKE ? OR javascript LIKE ? OR ruby LIKE ? OR python LIKE ?", "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%")
    end
    
end

app/controllers/snippets_controller.rb
class SnippetsController < ApplicationController

	before_action :find_snippet, only: [:show, :edit, :update, :destroy, :upvote, :dislike, :unvote]
	before_action :authenticate_user!, only: [:index, :show]
    before_action :authorized_user, only: [:edit, :update, :destroy]

	def index
		if params[:category].blank?
			@snippets = Snippet.all.desc
			if params[:search]
				@snippets = Snippet.search(params[:search]).desc
  			elsif
    			@snippets = Snippet.all.desc
    		end
		else 
			@category_id = Category.find_by(name: params[:category]).id
			@snippets = Snippet.where(category_id: @category_id).desc
		end
	end

	def show
	end

	def home
		@randomSnippet = Snippet.random
		@upvotedSnippet = Snippet.upvotedSnippet
		@totalVotes = Snippet.totalVotes
		@totalUpVotes = Snippet.totalUpVotes
		@totalDownVotes = Snippet.totalDownVotes
	end

	def new
		@snippet = current_user.snippets.build
	end

	def create
		@snippet = current_user.snippets.build(snippets_params)

		if @snippet.save
			redirect_to @snippet
		else
			render 'new'
		end
	end

	def edit
	end

	def update
		if @snippet.update(snippets_params)
			redirect_to @snippet
		else
			render 'edit'
		end
	end

	def destroy
		@snippet.destroy
		redirect_to root_path
	end

	def upvote
		@snippet.upvote_by current_user
		@snippet.user.increase_rep
		redirect_to :back
	end

	def dislike
        @snippet.downvote_by current_user
        @snippet.user.decrease_rep
        redirect_to :back
    end

    def unvote
    	@snippet.unvote_by current_user
    	@snippet.user.decrease_rep
    	redirect_to :back
  	end

	private

	def snippets_params
		params.require(:snippet).permit(:title, :css, :html, :javascript, :ruby, :python, :category_id, :search)
	end

	def find_snippet
		@snippet = Snippet.find(params[:id])
	end

	def authorized_user
        unless current_user.admin?
        	@snippet = current_user.snippets.find_by(id: params[:id])
        	redirect_to root_path if @snippet.nil?
        end
    end

end

app/helpers/snippets_helper.rb
module SnippetsHelper
end

app/views/snippets/_form.html.erb
<%= simple_form_for @snippet do |f| %>

    <div class="dropdown">
	   <%= f.collection_select :category_id, Category.all, :id, :name, {prompt: "Pick A Category"} %>
    </div>

    <div class="new-snippet">
    	<br><br>
        <%= f.input :title, label: "Title:", :input_html => {:id => "title-input"}, :error_html => { :class => "form-error"} %>
        <br><br>
        <%= f.input :css, label: "CSS:", input_html: { class: "code-input" }  %>
        <br>
        <%= f.input :html, label: "HTML:" %>
        <br>
        <%= f.input :javascript, label: "JavaScript:" %>
        <br>
        <%= f.input :ruby, label: "Ruby:" %>
        <br>
        <%= f.input :python, label: "Python:" %>
        <br>
        <%= f.button :submit %>
    </div>

<% end %>

app/views/snippets/css.html.erb
<div class="main">
	<div class="tab">
		<% Category.limit(4).each do |snippet| %>
	    	<p><%= link_to snippet.name, snippets_path(category: snippet.name) %></p>
	    <% end %>
	</div>
</div>

app/views/snippets/edit.html.erb
<div class="centered">
	<div class="edit">
		<h2>Edit Snippet</h2>
		<%= render 'form' %>
		<br>
		<%= link_to "Back", root_path %>
	</div>
</div>

app/views/snippets/home.html.erb
<div class="main">
	<div class="tab">
		<div class="home">
			<% unless user_signed_in? %>
				<p>Welcome. 
				<br>Please sign up to view and vote on our extensive range of code snippets.</p>
				<p>All snippets are easily available and have been tested across different major browsers.</p>
				<p>If you have an awesome &amp;&amp; || ingenious snippet you'd like to share, please <%= link_to "log in", new_user_session_path, class: "login" %> and post one!</p>
			<% else %>
				<p>Thanks for signing in!</p>
				<p>Navigate to a page via the top navigation bar, select a category and find a snippet.</p>
				<p>If you have snippet you'd like to share, please <u><%= link_to "post one", new_snippet_path %></u>.</p>
			<% end %>

			<div class="featured">
				<% @randomSnippet.each do |snippet| %>
					<p>Random snippet:<br><%= link_to snippet.title, snippet %></p>
				<% end %>
				<% @upvotedSnippet.each do |snippet| %>
					<p>Most upvoted snippet:<br><%= link_to snippet.title, snippet %></p>
				<% end %>
			</div>

			<p id="total-votes">Total votes cast: <%= @totalVotes %></p>
			<p id="total-votes">Total upvotes cast: <%= @totalUpVotes %></p>
			<p id="total-votes">Total downvotes cast: <%= @totalDownVotes %></p>
			
		</div>
		<p id="home-bottom"><span id="copyright">&copy;</span> Luka Kerr 2016. Built on Ruby &amp; PostgreSQL. | <%= link_to "About/Help", about_path %> | <%= link_to "Playground", playground_path %></p>
	</div>
</div>

app/views/snippets/index.html.erb
<div class="main">
	<div class="tab">
		<table>
			<% @snippets.each_slice(3) do |two_snippets| %>
			<tr>
				<% two_snippets.each do |snippet| %>
					<td><%= link_to snippet.title, snippet %></td>
				<% end %>
			</tr>
			<% end %>
		</table>

		<div class="no-snippets">
			<% if @snippets.blank? %>
				<p>No snippets found.</p>
				<br>&nbsp;<u><%= link_to "Back", :back %></u>
			<% end %>
		</div>
	</div>
</div>

app/views/snippets/javascript.html.erb
<div class="main">
	<div class="tab">
		<% Category.limit(4).offset(4).each do |snippet| %>
	    	<p><%= link_to snippet.name, snippets_path(category: snippet.name) %></p>
	    <% end %>
	</div>
</div>

app/views/snippets/new.html.erb
<div class="centered">
	<div class="new">
		<h2>New Snippet</h2>
		<div id="snippet-tooltip">
  			<p>Before posting code, make sure it works as
  			<br>expected. Test your code in the <%= link_to "playground", playground_path %>!</p>
  		</div>
  		<div id="code-tooltip">
  			<p>You must include at least one languages code
  			<br>in the snippet, otherwise you won't be able to post.</p>
  		</div>
		<%= render 'form' %>
		<br>
		<%= link_to "Back", root_path %>
	</div>
</div>

app/views/snippets/python.html.erb
<div class="main">
	<div class="tab">
	<% Category.limit(5).offset(13).each do |snippet| %>
    	<p><%= link_to snippet.name, snippets_path(category: snippet.name) %></p>
    <% end %>
	</div>
</div>

app/views/snippets/ruby.html.erb
<div class="main">
	<div class="tab">
	<% Category.limit(5).offset(8).each do |snippet| %>
    	<p><%= link_to snippet.name, snippets_path(category: snippet.name) %></p>
    <% end %>
	</div>
</div>

app/views/snippets/show.html.erb
<div class="centered">
	<div class="show">

		<% if @snippet.user.voted_up_on? @snippet %>

			<%= link_to unvote_snippet_path(@snippet), method: :put, class: "upvote-link" do %>
				<div class="tooltip">
					<%= image_tag("/assets/selectedup.png", class: "vote-images", id: "selected-up") %>
					<span class="tooltiptext tooltip-top">Click to unvote!</span>
				</div>
			<% end %>

			<%= link_to dislike_snippet_path(@snippet), method: :put, class: "upvote-link" do %>
				<div class="tooltip">
					<%= image_tag("/assets/down.png", class: "vote-images", id: "down") %>
					<span class="tooltiptext tooltip-top">This snippet isn't useful</span>
				</div>
			<% end %>

		<% elsif @snippet.user.voted_down_on? @snippet %>

			<%= link_to like_snippet_path(@snippet), method: :put, class: "upvote-link" do %>
				<div class="tooltip">
					<%= image_tag("/assets/up.png", class: "vote-images", id: "up") %>
					<span class="tooltiptext tooltip-top">This snippet is useful!</span>
				</div>
			<% end %>

			<%= link_to unvote_snippet_path(@snippet), method: :put, class: "upvote-link" do %>
				<div class="tooltip">
					<%= image_tag("/assets/selecteddown.png", class: "vote-images", id: "selected-down") %>
					<span class="tooltiptext tooltip-top">Click to unvote!</span>
				</div>
			<% end %>

		<% else %>

			<%= link_to like_snippet_path(@snippet), method: :put, class: "upvote-link" do %>
				<div class="tooltip">
					<%= image_tag("/assets/up.png", class: "vote-images", id: "up") %>
					<span class="tooltiptext tooltip-top">This snippet is useful!</span>
				</div>
			<% end %>

			<%= link_to dislike_snippet_path(@snippet), method: :put, class: "upvote-link" do %>
				<div class="tooltip">
					<%= image_tag("/assets/down.png", class: "vote-images", id: "down") %>
					<span class="tooltiptext tooltip-top">This snippet isn't useful</span>
				</div>
			<% end %>

		<% end %>

		<div class="snippet-vote-count">
			<span title="Click to show individual vote count"><%= @snippet.weighted_score %></span>
		</div>

		<div class="individual-vote-count snippet-vote-count">
		<% if @snippet.get_downvotes.size == 0 %>
			<%= @snippet.get_downvotes.size %>
		<% else %>
			-<%= @snippet.get_downvotes.size %>
		<% end %>
			<%= @snippet.get_upvotes.size %>
		</div>

		<h2><%= @snippet.title %> </h2>

		<% unless @snippet.css.blank? %>

		CSS<br> <%= raw Pygments.highlight(@snippet.css, :lexer => 'css') %>

		<% end %>

		<% unless @snippet.html.blank? %>

		HTML<br> <%= raw Pygments.highlight(@snippet.html, :lexer => 'html') %>

		<% end %>

		<% unless @snippet.javascript.blank? %>

		JavaScript<br> <%= raw Pygments.highlight(@snippet.javascript, :lexer => 'javascript') %>

		<% end %>

		<% unless @snippet.ruby.blank? %>

		Ruby<br> <%= raw Pygments.highlight(@snippet.ruby, :lexer => 'ruby') %>

		<% end %>

		<% unless @snippet.python.blank? %>

		Python<br> <%= raw Pygments.highlight(@snippet.python, :lexer => 'python') %>

		<% end %>

		<br>

		<h3 class="comments-title">
			<% if @snippet.comments.count == 1 %>
				<%= @snippet.comments.count %> Comment
			<% else %>
  				<%= @snippet.comments.count %> Comments
  			<% end %>
		</h3>

  		<%= render :partial => @snippet.comments %>

		<%= simple_form_for [@snippet, Comment.new]  do |f| %>
  			<div class="comment-input">
    			<%= f.text_area :body %>
  			</div>
  			<div id="comment-tooltip">
  				<p>To post code, wrap it in three backticks ` with the language after.
  				<br>Leave at least one line of space between text and code.
  				<br><br>For example: <br><br><i>This is some text<br><br>```python<br>code goes here<br>```</i></p>
  			</div>
  			<br>
  			<%= f.submit "Add Comment" %>
		<% end %>

		<br><br>

		<% if @snippet.user == current_user or current_user.admin? %>
			<%= link_to "Back", :back %>
			<%= link_to "Edit", edit_snippet_path(@snippet) %>
		<%= link_to "Delete", snippet_path(@snippet), method: :delete, data:{confirm: "Are you sure?"} %>
		<% else %>
			<%= link_to "Back", :back %>
		<% end %>

	</div>
</div>