config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations' }
  	resources :snippets do
  		member do
  			put "like", to: "snippets#upvote"
        put 'dislike', to: 'snippets#dislike'
        put 'unvote', to: 'snippets#unvote'
  		end
      
      resources :comments do
        member do
          put "like", to: "comments#upvote"
          put 'dislike', to: 'comments#dislike'
          put 'unvote', to: 'comments#unvote'
        end
      end
  	end

  	root 'snippets#home'

  	get '/css', to: 'snippets#css'
    get '/javascript', to: 'snippets#javascript'
    get '/ruby', to: 'snippets#ruby'
    get '/python', to: 'snippets#python'
    get '/about', to: 'sections#about'
    get '/playground', to: 'sections#playground'
    get 'users/leaderboard' => 'users#leaderboard'
    get '/users/:id', :to => 'users#show', :as => :user
end

app/views/layouts/_links.html.erb
<%= link_to "Home", root_path, class: "one" %>
<%= link_to "CSS", css_path, class: "two" %>
<%= link_to "JavaScript", javascript_path, class: "three" %>
<%= link_to "Ruby", ruby_path, class: "four" %>
<%= link_to "Python", python_path, class: "five" %>
<hr class="hr-one">

<div class="right-links">
	<% if user_signed_in? %>
			<%= link_to "New Snippet", new_snippet_path %>
			<%= link_to current_user.name, user_path(current_user) %>

			<div class="more-dropdown">
	  			<div class="more">
	  				<a>More</a>
	  			</div>
	  			<div class="dropdown-content">
	    			<%= link_to "About", about_path %>
	    			<%= link_to "Playground", playground_path %>
	    			<%= link_to "Leaderboard", users_leaderboard_path %>
	    			<%= link_to "Log Out", destroy_user_session_path, method: :delete %>
	  			</div>
			</div>

	<% else %>
		<%= link_to "Sign Up", new_user_registration_path, class: "signup" %>
		<%= link_to "Log In", new_user_session_path, class: "login" %>
	<% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Code Snippets</title>
	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	<%= csrf_meta_tags %>
	<meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>

	<nav>
		<%= render 'layouts/links' %>
		<div id="search">
			<%= form_tag(snippets_path, :method => "get", id: "search-form") do %>
			<%= text_field_tag :search, params[:search], placeholder: "search" %>
			<% end %>
		</div>
	</nav>

	<div class="nav2">
		<span class="menubutton">
			<span class="bar"></span>
			<span class="bar"></span>
			<span class="bar"></span>
		</span>
		
		<div class="dropdown-nav">
			<div class="dropdown-nav-links">
				<%= render 'layouts/links' %>
			</div>
		</div>
	</div>

	<div class="centered">
		<p class="notice fade"><%= notice %></p>
		<p class="alert fade"><%= alert %></p>
	</div>

	<%= yield %>

</body>
</html>